### ISSUE TITLE
Training code issue on OpenOOD

### ISSUE THREAD

**Issue by zjysteven** [kai422/SCALE#1]
Hi Kai,

Thank you again for previously contributing ISH to OpenOOD. We saw an issue (https://github.com/Jingkang50/OpenOOD/issues/224) that reported error during the forward pass of ISH model, causing training failure, and I could reproduce the bug. Would you mind taking a look at it and pushing fixes?

Thanks,
Jingyang

**Comment by kai422** [comment]
fixed :)
